workflows:
  build_and_distribute_android:
    name: Build, Test, and Distribute Android App
    max_build_duration: 60 # Set max build duration in minutes
    triggers:
      - push # Trigger builds on every push
      - pull_request # Trigger builds on pull requests
    steps:
      - name: Install dependencies
        run: flutter pub get
      - name: Run tests
        run: flutter test
      - name: Build Android APK
        run: flutter build apk --debug # Build in debug mode (not release)
    #   - name: Upload to Firebase App Distribution
    #     run: |
    #       firebase appdistribution:distribute build/app/outputs/flutter-apk/app-debug.apk \
    #       --app <your-firebase-android-app-id> \
    #       --groups "Testers" \
    #       --token <your-firebase-token> \
    #       --testers "tester1@example.com,tester2@example.com"
